### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lunik1981** [PixelExperience/frameworks_opt_telephony#1]
12-08 21:53:42.876 30452 30452 E AndroidRuntime: FATAL EXCEPTION: main

12-08 21:53:42.876 30452 30452 E AndroidRuntime: Process: com.android.phone, PID: 30452

12-08 21:53:42.876 30452 30452 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Lcom/android/internal/telephony/Phone;)V in class Lcom/android/internal/telephony/dataconnection/DcTracker; or its super classes (declaration of 'com.android.internal.telephony.dataconnection.DcTracker' appears in /system/framework/telephony-common.jar)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.dataconnection.QtiDcTracker.<init>(QtiDcTracker.java:69)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory.makeDcTracker(QtiTelephonyComponentFactory.java:72)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.android.internal.telephony.GsmCdmaPhone.<init>(GsmCdmaPhone.java:227)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiGsmCdmaPhone.<init>(QtiGsmCdmaPhone.java:77)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiGsmCdmaPhone.<init>(QtiGsmCdmaPhone.java:70)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory.makePhone(QtiTelephonyComponentFactory.java:149)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhone(PhoneFactory.java:193)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhones(PhoneFactory.java:99)

12-08 21:53:42.876 30452 30452 E AndroidRuntime: 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:286)

**Comment by jhenrique09** [comment]
Fix your blobs
